version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: build
          command: ./gradlew clean build check
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          when: always
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  deploy:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch
    environment:
      APP_NAME: htbhf-os-places
      SMOKE_TESTS: ./ci_scripts/smoke_tests.sh
      BIN_DIR: ./bin
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "25:d9:4e:0f:53:75:80:8f:8d:7c:79:64:c9:3d:b4:a6"
      - attach_workspace:
          at: .
      - run:
          name: Set app version and path
          command: |
            export APP_VERSION=`cat version.properties | grep "version" | cut -d'=' -f2`
            echo "export APP_VERSION=${APP_VERSION}" >> $BASH_ENV
            echo "export APP_PATH="build/libs/$APP_NAME-$APP_VERSION.jar"" >> $BASH_ENV
            source $BASH_ENV
            echo "APP_VERSION=${APP_VERSION}, APP_PATH=${APP_PATH}"
      - run:
          name: set TRAVIS_BRANCH as this is required by shipkit
          command: |
            echo "export TRAVIS_BRANCH=$CIRCLE_BRANCH" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: release
          command: ./gradlew ciPerformRelease -s
      - run:
          name: deploy to dev
          command: ./ci_scripts/ci_deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
